# Site settings
title: Mobbex
subtitle: Developer Site
email: info@mobbex.com
description: Desde aquí podras acceder a toda la documentación necesaria para implementar Mobbex en tu sitio o sistema.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mobbexco.github.io" # the base hostname & protocol for your site
author: Mobbex, Co

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 3

# Social settings
facebook_url: https://facebook.com/mobbex
github_url: https://github.com/mobbexco
twitter_url: https://twitter.com/mobbex

# Build settings
markdown: kramdown
